### ISSUE TITLE
Files aren't being generated

### ISSUE THREAD

**Issue by tamj0rd2** [ngeor/generator-csharp-cli-app#5]
OS: Windows 10 64-bit
generator-csharp-cli-app version: 0.1.2
npm version: 4.0.5
node version: 6.9.2

All of the console output:
```
$ yo csharp-cli-app
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
? Your project name UpdateChromium
? Company name (for AssemblyInfo.cs copyright fields) tamj0rd2
```

**Comment by ngeor** [comment]
Confirmed. Working on a fix to upgrade to the latest yeoman-generator package.

**Comment by ngeor** [comment]
Please upgrade to latest release (v0.2.0), thanks for reporting this issue!
