### ISSUE TITLE
No generator found after install

### ISSUE THREAD

**Issue by pfmmfp** [ngeor/generator-csharp-cli-app#7]
Hi!

I've just installed the generator using `npm` as specified in the readme but when running `yo csharp-cli-app` I'm getting,

`You don't seem to have a generator with the name csharp-cli-app installed.`

I checked with `yo --help` and the generator is not in the list.

Any hint is appreciated! Thanks you!

**Comment by ngeor** [comment]
Hello,

that's odd. Could you please share the versions of `node`, `npm` and `yo` that you are using? You can also do a `npm list -g -depth 0` to see the globally installed node packages. The generator should be in there too.

**Comment by pfmmfp** [comment]
Ah! My `yo` was super old. Working now! Sorry and thanks a lot for your help!
